### ISSUE TITLE
Maybe we can disable some warnings.

### ISSUE THREAD

**Issue by Timandes** [andreiz/php-zookeeper#49]
When something was going wrong, it returns false.

We could get error code & message from getResultCode() & getResultMessage() just like php_memcached.

    <?php

    $zk = new Zookeeper('localhost:2181');
    $r = $zk->set('/test', 123);
    if (!$r) {
        echo $zk->getResultMessage() . "(#" . $zk->getResultCode() . ")";
    }
    echo "Done";

**Comment by fabiorphp** [comment]
The best way to do this, is implement exceptions.

**Comment by Timandes** [comment]
@fabiorphp Could we handle this just like mysqli_driver::$report_mode?

**Comment by andreiz** [comment]
I really dislike mysqli_driver::$report_mode. There should be just one way to gather error information.

**Comment by fabiorphp** [comment]
Seriously, I don't like report mode. 
In my humble opinion, we should think about exceptions. The correct use of exceptions, I believe that will be the best choice.

**Comment by Timandes** [comment]
All right, then.
If you guys both like exceptions, should we start merging pull request #28?
Or you have other plans?

**Comment by fabiorphp** [comment]
Maybe, but for do that, we should check the entire PR commits and create tests for it, maybe use this PR for think in an ideia to make this possible

**Comment by Timandes** [comment]
@andreiz 
Could you create a new branch in order to complete feature about exceptions?

**Comment by andreiz** [comment]
@Timandes done

**Comment by Timandes** [comment]
@andreiz :heart_eyes:

**Comment by fabiorphp** [comment]
:smile: Please close this issue!
