### ISSUE TITLE
Travis-CI and Coveralls

### ISSUE THREAD

**Issue by fabiorphp** [andreiz/php-zookeeper#56]
Guys!

Which is the possibility to integrate with Travis-CI and Coveralls?

**Comment by Timandes** [comment]
I'll help.

**Comment by fabiorphp** [comment]
Could you give me access to configure travis-ci?

**Comment by andreiz** [comment]
How do I do that?

**Comment by fabiorphp** [comment]
Well, You need to create a team in repository settings and set the permissions.

**Comment by Timandes** [comment]
@fabiorphp  like php-memcached-dev ?

**Comment by fabiorphp** [comment]
What?

No, I need access to the repository to configure Travis-CI and Coveralls.

**Comment by andreiz** [comment]
@fabiorphp I added you as a collaborator. Is that going to be enough?

**Comment by fabiorphp** [comment]
Maybe not, but don't worry, if you integrate Travis-CI and Coveralls is enough, so we can approve pull-request only if travis returns ok.

**Comment by fabiorphp** [comment]
And create an account in Coveralls for code coverage.
