### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by rafaelbecks** [andreiz/php-zookeeper#63]
Hey people!

I'm following [these instructions][2] and I'm getting this error when running `./configure` after `phpize`:

> configure: error: Can't find zookeeper headers under "/usr/share/zookeeper"

I already verified that the path exists, and I also tried to install via `pecl`. That gives the same error (with other versions of the extension too).

How do I resolve this?

  [1]: https://github.com/quipo/kafka-php
  [2]: https://github.com/Qihoo360/logkafka/blob/master/docs/install-php-zookeeper-extension.md

**Comment by Timandes** [comment]
Make sure you have installed the Zookeeper C Client first.

发自我的 iPhone

**Comment by rafaelbecks** [comment]
Do you mean this package? https://packages.debian.org/wheezy/zookeeperd . I installed zookeeper using 
>sudo apt-get install zookeeperd

I'm installing it just in order to use php-kafka

**Comment by Timandes** [comment]
Try libzookeeper-mt-dev.



Timandes White
 
From: Rafael Angel Becerra Blasco
Date: 2015-10-27 09:53
To: andreiz/php-zookeeper
CC: Timandes White
Subject: Re: [php-zookeeper] Error while installing (#63)
Do you mean this package? https://packages.debian.org/wheezy/zookeeperd . I installed zookeeper using 
sudo apt-get install zookeeperd
I'm installing it just in order to use php-kafka

**Comment by rafaelbecks** [comment]
Thanks a lot! , I installed that package, I could not build it from source (maybe I'm loosing something in the specification path) but I could installed it via pecl. So, it's done!

**Comment by theofilos13** [comment]
I thing _/usr/_ is fine, as it is showed bellow.
Usually zookeeper headers are on _/usr/include/zookeeper_ 


To enable zookeeper support, configure with --with-libzookeeper-dir=DIR . DIR is the install prefix of ZooKeeper C Binding, which **must contain the include/zookeeper/zookeeper.h**

http://php.net/manual/en/zookeeper.installation.php
