### ISSUE TITLE
how to install with php7?

### ISSUE THREAD

**Issue by HeiHeiHeiHeiHeiHH** [andreiz/php-zookeeper#83]
when i do the command 'make', it tells me this:

      the file or dir is not exists : ext/standard/php_smart_str.h

what's wrong with this? or It doesn't support php7 ?

**Comment by Timandes** [comment]
Try pecl/zookeeper?

**Comment by HeiHeiHeiHeiHeiHH** [comment]
I did it ,but also show this proble.

**Comment by Timandes** [comment]
Would you please provide your full output lines of `make`?

**Comment by HeiHeiHeiHeiHeiHH** [comment]
![qq 20170428110111](https://cloud.githubusercontent.com/assets/24953493/25512669/06fe1074-2c02-11e7-9e05-3be2cdfa4a27.png)

**Comment by HeiHeiHeiHeiHeiHH** [comment]
and cause my php version is 7.0 ,so i did the command phpize7.0 at first

**Comment by Timandes** [comment]
First, I found an empty line in php_zookeeper.c:38. So, please be sure that you are using the newest version.

Second, if you are using PHP 7.0, it will include `<ext/standard/php_smart_string.h>` other than `<ext/standard/php_smart_str.h>`.

**Comment by HeiHeiHeiHeiHeiHH** [comment]
大哥你好像是国人吧 = =   我就不扯英文了，水平太差。
还是那个问题，我修改了那个<ext/standard/php_smart_sting.h>
虽然make没有卡住了可是，出现了很多错误提示，哦 对了，改了文件是不是也要重新编译一下那个.c 文件 =  =
![qq 20170428141209](https://cloud.githubusercontent.com/assets/24953493/25516352/ba60d90c-2c1c-11e7-8cf0-e19b50bd91e5.png)

**Comment by Timandes** [comment]
1. 在我这边的代码中`php_zookeeper.c:38`是空行，所以确保你使用的是最新版本的代码；

2. 根据你的截图，你最后的报错提示是“找不到`ext/standard/php_smart_str.h`”。但是在`php-zookeeper`的代码里明确给出了，如果你使用的是PHP-7，引用的是`ext/standard/php_smart_string.h`。我觉着你的PHP版本有些混乱……

**Comment by Timandes** [comment]
问题是否已经得到解决？

**Comment by HeiHeiHeiHeiHeiHH** [comment]
Yes....
________________________________________
发件人: Timandes White [notifications@github.com]
发送时间: 2018年1月1日 20:07
收件人: andreiz/php-zookeeper
抄送: 刘忠其; Author
主题: Re: [andreiz/php-zookeeper] how to install with php7? (#83)

问题是否已经得到解决？

―

**Comment by Timandes** [comment]
那可否关闭这个Issue？ : )

**Comment by HeiHeiHeiHeiHeiHH** [comment]
不好意思，已关闭～
________________________________________
发件人: Timandes White [notifications@github.com]
发送时间: 2018年1月2日 18:21
收件人: andreiz/php-zookeeper
抄送: 刘忠其; Author
主题: Re: [andreiz/php-zookeeper] how to install with php7? (#83)

那可否关闭这个Issue？ : )

―

**Comment by liron-li** [comment]
能说一下怎么解决的么？我遇到了同样的问题。

**Comment by HeiHeiHeiHeiHeiHH** [comment]
装zk的时候， 里面有个东西要再装一次到一个你制定的路径， 然后装这个扩展的时候带进去就可以了。 我记得好像是这个步骤。 原因是少了个libzookeep
________________________________________
发件人: Liron [notifications@github.com]
发送时间: 2018年3月20日 11:04
收件人: andreiz/php-zookeeper
抄送: 刘忠其; State change
主题: Re: [andreiz/php-zookeeper] how to install with php7? (#83)

能说一下怎么解决的么？我遇到了同样的问题。

―

**Comment by liron-li** [comment]
@HeiHeiHeiHeiHeiHH  有指定路径的　还是不行。
后来我找到了　[https://github.com/php-zookeeper/php-zookeeper](url)　这个项目，然后就一次编译成功了。
这个项目貌似是fork出来的　由 @Timandes 大哥在维护的，不知道这两个项目有什么区别。 @Timandes 　能说说为什么要fork出来，而不在原有项目上提ＰＲ吗

**Comment by liron-li** [comment]
@Timandes  给大哥点赞 ，开源社区需要您这样的人

**Comment by sumanchoudhary** [comment]
I am are using PHP 7.0,I have replaced 

> <ext/standard/php_smart_str.h>

 with 

> <ext/standard/php_smart_string.h> 

but found the same error.
![image](https://user-images.githubusercontent.com/12594024/41599439-d1c03e5e-73f0-11e8-8ab2-f2501ee4171f.png)


.

**Comment by Timandes** [comment]
Would you provide version infos?

**Comment by sumanchoudhary** [comment]
PHP version info:

![image](https://user-images.githubusercontent.com/12594024/41641010-697f7634-7481-11e8-9dc7-977e438ed105.png)

**Comment by Timandes** [comment]
What about php-zookeeper?

**Comment by sumanchoudhary** [comment]
zookeeper-3.4.12

**Comment by Timandes** [comment]
Version of php-zookeeper. Not zookeeper.
